name: Android APK Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Project Zip
        run: unzip aurawavex.zip -d project_folder

      - name: Check Extracted Folder Structure
        run: ls -R project_folder
        
